language: python
python:
  - "3.8"
cache: pip

matrix:
    include:
        - python: "3.8"
          env: TOXENV=py38
        - python: "3.8"
          env: TOXENV=lint

install:
  - pip install -r requirements.txt
  - pip install -U tox
script:
  - tox
